init:
  _target_: fedlib.standard.models.FedNCFModel
  gmf_emb_size: 16
  mlp_emb_size: 64
  mlp_layer_dims: [128, 64, 32, 16]
  dropout: 0.0
name: fedncf${net.init.gmf_emb_size}-${net.init.mlp_emb_size}