# @package _global_
defaults:
  - _self_
  - data: ml-1m.yaml
  - net: fedmf16.yaml
  - compression: none.yaml
  - paths: default.yaml
  - hydra: default.yaml
  # config for hyperparameter optimization
  - hparams_search: null

FED:
  num_clients: 120
  agg_epochs: 400
  local_epochs: 2
  compression_kwargs:
    method: 'none'
  aggregation: 'fedavg'

DATA:
  root: '../data/Data'
  name: 'movielens'
  num_negatives: 4
  test_num_ng: 99

DATALOADER:
  batch_size: 256
  shuffle: True
  num_workers: 0

TRAIN:
  optimizer: sgd
  lr: 1e-2
  weight_decay: 0
  lr_scheduler: None
  device: 'cuda'
  wandb: False
  log_interval: 10

EVAL:
  topk: 10
  interval: 100

EXP:
  seed: 42
  project: 'lora-fedrec-3'


task_name: fedtrain
run_name: ${DATA.name}
# ${now:%Y-%m-%d}_${now:%H-%M-%S}
